services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    command: gunicorn --worker-class gevent --threads 4 --bind 0.0.0.0:5000 app.app:server
    expose:
      - 5000
    env_file:
      - ./.env

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    environment:
      - DOMAIN
    depends_on:
      - web
    ports:
      - 80:80
    volumes:
      - ./services/nginx/templates:/etc/nginx/templates:ro

