from .driver_career import driver_career
from .driver_perf_this_season import driver_perf_this_season
from .driver_profile import driver_profile
from .driver_standing import driver_standing
from .event_title_and_weather import event_title_and_weather
from .interesting_fact import interesting_fact
from .lap_time_comparison import lap_time_comparison
from .navbar import navbar
from .position_comparison import position_comparison
from .prediction_vs_actual_table import prediction_vs_actual_table
from .prediction_vs_actual_top3 import prediction_vs_actual_top3
from .team_standing import team_standing
from .track_info import track_info
from .track_perf import track_perf
from .tyre_strategy import tyre_strategy
import dash_bootstrap_components as dbc
